### ISSUE TITLE
Get requests send identifier information in the param

### ISSUE THREAD

**Issue by robwasripped** [thesalegroup/restorm#13]
## Expected Behavior
When a request is made that includes the identifier of a resource to an endpoint that has that ID as part of the path, the identifier should be removed from the parameters. Currently this is being presented:
`http://example.com/resource/123?id=123 `

## Actual Behavior
The identifier should be removed from the params when the identifier is given in the path:
`http://example.com/resource/123`

## Steps to Reproduce the Problem

  1. Send a GET (findOne) request to an endpoint that includes the identifier in the path.

**Comment by Kadonite** [comment]
Fixes #13

## Proposed Changes

  - modifying the QueryBuilder::getEndpoint method to remove the getIdentifierName from the Query filter if it is contained within the requested path.
